# Generated by Django 3.1 on 2021-04-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20210407_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='delivery_order_nuo',
            new_name='delivery_order_no',
        ),
    ]
